### ISSUE TITLE
Why are not creating multiple db? just create "docker" database, why?

### ISSUE THREAD

**Issue by manel00** [mrts/docker-postgresql-multiple-databases#11]
I'm trying to do as a volume option, but there is some step I missed.

Thank you very much

**Comment by mrts** [comment]
Hi @manel00! Can you be a bit more specific - what script lines did you write exactly? What error messages did you see?

**Comment by manel00** [comment]
Hi, exactly what you gives, when i'm doing on my computer that project, it fails, please explain exactly what should be done to run it,

Thanks, seems interesting!



Enviado desde mi Redmi Note 4
El Mart Sõmermaa <notifications@github.com>, 12 abr. 2018 5:54 p. m. escribió:

Hi @manel00<https://github.com/manel00>! Can you be a bit more specific - what script lines did you write exactly? What error messages did you see?

**Comment by mrts** [comment]
Closing, please reopen with steps to reproduce and error message you see if you like!
