### ISSUE TITLE
Creating new database on top of existing one

### ISSUE THREAD

**Issue by gotexis** [mrts/docker-postgresql-multiple-databases#14]
Hey,

I have an existing docker-compose with an existing database.

volume1 - db1
             
Now I think I need another one.

volume1 - db1, db2

If I build a custom image like suggested, but keep using the same mounted volume, would I be able to have my current database unaffected?

**Comment by mrts** [comment]
I have to admit that I'm not sure. Did you try this, did it work?

**Comment by fpalluel** [comment]
Hello,
Unfortunately the initialization process is not rerun if  ANY database  already exists, see https://github.com/docker-library/postgres/blob/master/11/docker-entrypoint.sh

So, as is, it seems to be impossible to create a new database without erasing the previous existing ones.

**Comment by mrts** [comment]
@fpalluel closing as not possible
