### ISSUE TITLE
Rights to users

### ISSUE THREAD

**Issue by Pavlo-Olshansky** [mrts/docker-postgresql-multiple-databases#16]
https://github.com/mrts/docker-postgresql-multiple-databases/blob/ac7f26d2101b5579b3f7ecc627a8e715f49eb7eb/create-multiple-postgresql-databases.sh#L12
Is that should be a user, not database ? Like this:
GRANT ALL PRIVILEGES ON DATABASE $database TO $POSTGRES_USER;
Not like this:
GRANT ALL PRIVILEGES ON DATABASE $database TO $database;

**Comment by mrts** [comment]
The user `$database` is created on [line 10](https://github.com/mrts/docker-postgresql-multiple-databases/blob/ac7f26d2101b5579b3f7ecc627a8e715f49eb7eb/create-multiple-postgresql-databases.sh#L10), so this is intentional.
