### ISSUE TITLE
This is weird...

### ISSUE THREAD

**Issue by sandipndev** [mrts/docker-postgresql-multiple-databases#18]
First the database is created and then when requested for, it doesn't seem to present (last line)
![image](https://user-images.githubusercontent.com/40622610/103106898-6b3e1400-465f-11eb-90e8-e4b4ab8edaa7.png)

**Comment by mrts** [comment]
Hi Sandip! This expected behaviour and documented in the [README](https://github.com/mrts/docker-postgresql-multiple-databases#non-standard-database-names): _If you need to use non-standard database names (hyphens, uppercase letters etc), quote them_.

**Comment by sandipndev** [comment]
Yess, I later found out that apparently postgresql converts all database names to lowercase. So the ‘appDb’ turned out at ‘appdb’.
